"use client";

import { ChevronRightIcon, SearchIcon } from "@/components/ui/icons";
import { cn } from "@/lib/cn";
import { useMemo, useState } from "react";
import { companyAdminReports } from "../data/companyAdminDashboardData";
import type { CompanyReportStatus } from "../schemas/companyAdminDashboardSchemas";
import { formatReportDateTime } from "../utils/formatReportDateTime";
import { DashboardPagination } from "./DashboardPagination";
import {
  DashboardStatusFilter,
  type DashboardStatusFilterOption,
} from "./DashboardStatusFilter";
import { DashboardStatusPill } from "./DashboardStatusPill";

const ROWS_PER_PAGE = 6;

type CompanyReportStatusFilterValue = CompanyReportStatus | "all";

const COMPANY_STATUS_FILTER_OPTIONS = [
  { value: "all", label: "All Status" },
  { value: "completed", label: "Completed" },
  { value: "sent_for_review", label: "Sent for Review" },
  { value: "in_progress", label: "In Progress" },
  { value: "reviewed", label: "Reviewed" },
  { value: "failed", label: "Failed" },
] as const satisfies readonly DashboardStatusFilterOption<CompanyReportStatusFilterValue>[];

const companyReportRowClass =
  "grid min-w-[1404px] grid-cols-[minmax(380px,1fr)_180px_230px_240px_150px_24px] items-center gap-x-10 px-6";

export function CompanyReportsTable() {
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] =
    useState<CompanyReportStatusFilterValue>("all");
  const [currentPage, setCurrentPage] = useState(1);

  const filteredReports = useMemo(() => {
    const normalizedSearch = searchQuery.trim().toLocaleLowerCase();

    return companyAdminReports.filter((report) => {
      const matchesStatus =
        statusFilter === "all" || report.status === statusFilter;
      const matchesSearch =
        normalizedSearch.length === 0 ||
        report.title.toLocaleLowerCase().includes(normalizedSearch) ||
        report.generatedBy.toLocaleLowerCase().includes(normalizedSearch) ||
        report.userEmail.toLocaleLowerCase().includes(normalizedSearch);

      return matchesStatus && matchesSearch;
    });
  }, [searchQuery, statusFilter]);

  const totalPages = Math.max(
    1,
    Math.ceil(filteredReports.length / ROWS_PER_PAGE),
  );
  const safeCurrentPage = Math.min(currentPage, totalPages);
  const visibleReports = filteredReports.slice(
    (safeCurrentPage - 1) * ROWS_PER_PAGE,
    safeCurrentPage * ROWS_PER_PAGE,
  );

  const handleSearchChange = (value: string) => {
    setSearchQuery(value);
    setCurrentPage(1);
  };

  const handleStatusFilterChange = (value: CompanyReportStatusFilterValue) => {
    setStatusFilter(value);
    setCurrentPage(1);
  };

  return (
    <section aria-label="Company reports">
      <div className="overflow-hidden rounded-button border border-border-default bg-surface-default">
        <div className="flex flex-col gap-4 px-6 py-4 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="text-card-title font-medium text-white">Reports</h2>

          <div className="flex w-full flex-col gap-3 sm:max-w-[664px] sm:flex-1 sm:flex-row sm:items-center sm:gap-4">
            <label className="relative block w-full sm:flex-1">
              <span className="sr-only">Search report name or users</span>
              <span className="pointer-events-none absolute top-1/2 left-5 -translate-y-1/2 text-white/28">
                <SearchIcon />
              </span>
              <input
                type="search"
                value={searchQuery}
                placeholder="Search report name, users"
                onChange={(event) => handleSearchChange(event.target.value)}
                className="h-14 w-full rounded-button bg-surface-subtle py-4 pr-5 pl-14 text-body-lg text-white outline-none placeholder:text-white/28 focus:ring-1 focus:ring-border-default"
              />
            </label>

            <DashboardStatusFilter
              value={statusFilter}
              options={COMPANY_STATUS_FILTER_OPTIONS}
              showSelectedLabel
              onChange={handleStatusFilterChange}
            />
          </div>
        </div>

        <div className="overflow-x-auto">
          <div
            className={cn(
              companyReportRowClass,
              "h-14 bg-surface-subtle text-label font-medium text-text-step",
            )}
          >
            <span>Report Name</span>
            <span>Generated by</span>
            <span>User Email</span>
            <span>Last Updated</span>
            <span>Status</span>
            <span className="sr-only">Open</span>
          </div>

          <div className="flex flex-col">
            {visibleReports.length === 0 ? (
              <p className="px-6 py-10 text-center text-label text-text-muted">
                No company reports match your search or status filter.
              </p>
            ) : (
              visibleReports.map((report, index) => (
                <div
                  key={report.id}
                  className={cn(
                    companyReportRowClass,
                    "h-[86px] border-b border-border-subtle text-left transition-colors last:border-b-0 hover:bg-brand-bg",
                  )}
                >
                  <span className="flex min-w-0 items-center gap-4">
                    <span className="inline-flex size-7 shrink-0 items-center justify-center rounded-toggle-knob bg-surface-elevated text-input font-medium text-white">
                      {(safeCurrentPage - 1) * ROWS_PER_PAGE + index + 1}
                    </span>
                    <span className="truncate text-label font-medium text-white">
                      {report.title}
                    </span>
                  </span>

                  <span className="truncate text-label font-medium text-white">
                    {report.generatedBy}
                  </span>

                  <span className="truncate text-label font-medium text-white">
                    {report.userEmail}
                  </span>

                  <span className="text-label font-medium whitespace-nowrap text-white">
                    {formatReportDateTime(report.updatedAt)}
                  </span>

                  <span className="justify-self-start">
                    <DashboardStatusPill status={report.status} />
                  </span>

                  <ChevronRightIcon className="justify-self-end text-white" />
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {totalPages > 1 ? (
        <div className="mt-4 px-2">
          <DashboardPagination
            currentPage={safeCurrentPage}
            totalPages={totalPages}
            onPageChange={setCurrentPage}
          />
        </div>
      ) : null}
    </section>
  );
}
